pi=3.1416
r=float(input("Ingrese el radio del circulo: "))
print()
print("La superficie del circulo es ",pi * r**2)
print()
print ("El perimetro de la circunferencia es :",pi * 2*r )
print()
print ("La superficie de la esfera es: ",4*pi*r**2)
print()
print ("El volumen de la esfera es : ", 1.33*pi*r**3)
print()
